import { promises as fs } from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { chromium, firefox, webkit, type Browser, type BrowserContext, type Page } from "playwright";
import type { ToolDefinition } from "./types.js";
import { asObject, optionalBoolean, optionalNumber, optionalString, requiredString } from "./runtime.js";
interface BrowserSession { id: string; browser: Browser; context: BrowserContext; page: Page; console: Array<Record<string, unknown>>; network: Array<Record<string, unknown>>; }
const sessions = new Map<string, BrowserSession>();
function getSession(id: string): BrowserSession { const session = sessions.get(id); if (!session) throw new Error(`Sessão de navegador não encontrada: ${id}`); return session; }
export const browserTools: ToolDefinition[] = [
  { name: "browser_open", description: "Abre URL em Chromium, Firefox ou WebKit e cria uma sessão reutilizável.", risk: "execute", inputSchema: { type: "object", properties: { url: { type: "string" }, browser: { type: "string", enum: ["chromium", "firefox", "webkit"] }, headless: { type: "boolean" }, width: { type: "number" }, height: { type: "number" }, timeoutMs: { type: "number" } }, required: ["url"], additionalProperties: false }, async execute(input) { const values = asObject(input); const name = optionalString(values, "browser", "chromium")!; const browserType = name === "firefox" ? firefox : name === "webkit" ? webkit : chromium; const browser = await browserType.launch({ headless: optionalBoolean(values, "headless", true) }); const context = await browser.newContext({ viewport: { width: optionalNumber(values, "width", 1440), height: optionalNumber(values, "height", 900) } }); const page = await context.newPage(); const id = randomUUID(); const session: BrowserSession = { id, browser, context, page, console: [], network: [] }; page.on("console", (message) => session.console.push({ type: message.type(), text: message.text(), at: new Date().toISOString() })); page.on("pageerror", (error) => session.console.push({ type: "pageerror", text: error.message, at: new Date().toISOString() })); page.on("response", (response) => { if (response.status() >= 400) session.network.push({ url: response.url(), status: response.status(), method: response.request().method() }); }); page.on("requestfailed", (request) => session.network.push({ url: request.url(), method: request.method(), error: request.failure()?.errorText })); sessions.set(id, session); const response = await page.goto(requiredString(values, "url"), { waitUntil: "domcontentloaded", timeout: optionalNumber(values, "timeoutMs", 30_000) }); return { sessionId: id, browser: name, url: page.url(), title: await page.title(), status: response?.status() ?? null }; } },
  { name: "browser_snapshot", description: "Retorna URL, título, texto visível e opcionalmente HTML da página.", risk: "read", inputSchema: { type: "object", properties: { sessionId: { type: "string" }, includeHtml: { type: "boolean" }, maxChars: { type: "number" } }, required: ["sessionId"], additionalProperties: false }, async execute(input) { const values = asObject(input); const session = getSession(requiredString(values, "sessionId")); const max = Math.max(1, optionalNumber(values, "maxChars", 100_000)); const text = (await session.page.locator("body").innerText()).slice(0, max); const html = optionalBoolean(values, "includeHtml") ? (await session.page.content()).slice(0, max) : undefined; return { sessionId: session.id, url: session.page.url(), title: await session.page.title(), text, html }; } },
  { name: "browser_screenshot", description: "Captura screenshot e retorna imagem MCP, além de salvar opcionalmente no workspace.", risk: "read", inputSchema: { type: "object", properties: { sessionId: { type: "string" }, path: { type: "string" }, fullPage: { type: "boolean" }, selector: { type: "string" } }, required: ["sessionId"], additionalProperties: false }, async execute(input, context) { const values = asObject(input); const session = getSession(requiredString(values, "sessionId")); const file = optionalString(values, "path"); const target = file ? context.resolvePath(file) : undefined; if (target) await fs.mkdir(path.dirname(target), { recursive: true }); const selector = optionalString(values, "selector"); const buffer = selector ? await session.page.locator(selector).screenshot({ path: target }) : await session.page.screenshot({ path: target, fullPage: optionalBoolean(values, "fullPage", true) }); return { content: [{ type: "image", data: buffer.toString("base64"), mimeType: "image/png" }], sessionId: session.id, path: target, bytes: buffer.byteLength }; } },
  { name: "browser_click", description: "Clica em um elemento por locator Playwright.", risk: "execute", inputSchema: { type: "object", properties: { sessionId: { type: "string" }, selector: { type: "string" }, timeoutMs: { type: "number" } }, required: ["sessionId", "selector"], additionalProperties: false }, async execute(input) { const values = asObject(input); const session = getSession(requiredString(values, "sessionId")); await session.page.locator(requiredString(values, "selector")).click({ timeout: optionalNumber(values, "timeoutMs", 30_000) }); return { sessionId: session.id, url: session.page.url() }; } },
  { name: "browser_fill", description: "Preenche um campo usando locator Playwright.", risk: "execute", inputSchema: { type: "object", properties: { sessionId: { type: "string" }, selector: { type: "string" }, value: { type: "string" } }, required: ["sessionId", "selector", "value"], additionalProperties: false }, async execute(input) { const values = asObject(input); const session = getSession(requiredString(values, "sessionId")); await session.page.locator(requiredString(values, "selector")).fill(requiredString(values, "value")); return { sessionId: session.id }; } },
  { name: "browser_evaluate", description: "Executa JavaScript serializável na página ativa.", risk: "execute", inputSchema: { type: "object", properties: { sessionId: { type: "string" }, expression: { type: "string" } }, required: ["sessionId", "expression"], additionalProperties: false }, async execute(input) { const values = asObject(input); const session = getSession(requiredString(values, "sessionId")); const expression = requiredString(values, "expression"); const value = await session.page.evaluate((source) => (0, eval)(source), expression); return { sessionId: session.id, value }; } },
  { name: "browser_console", description: "Retorna mensagens de console e erros da página.", risk: "read", inputSchema: { type: "object", properties: { sessionId: { type: "string" }, clear: { type: "boolean" } }, required: ["sessionId"], additionalProperties: false }, async execute(input) { const values = asObject(input); const session = getSession(requiredString(values, "sessionId")); const messages = [...session.console]; if (optionalBoolean(values, "clear")) session.console.length = 0; return { sessionId: session.id, messages }; } },
  { name: "browser_network", description: "Retorna respostas HTTP com erro e requests falhos observados.", risk: "read", inputSchema: { type: "object", properties: { sessionId: { type: "string" }, clear: { type: "boolean" } }, required: ["sessionId"], additionalProperties: false }, async execute(input) { const values = asObject(input); const session = getSession(requiredString(values, "sessionId")); const events = [...session.network]; if (optionalBoolean(values, "clear")) session.network.length = 0; return { sessionId: session.id, events }; } },
  { name: "browser_close", description: "Fecha contexto e navegador da sessão.", risk: "destructive", inputSchema: { type: "object", properties: { sessionId: { type: "string" } }, required: ["sessionId"], additionalProperties: false }, async execute(input) { const id = requiredString(asObject(input), "sessionId"); const session = getSession(id); await session.context.close(); await session.browser.close(); sessions.delete(id); return { sessionId: id, closed: true }; } }
];
