import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";
import { randomUUID } from "node:crypto";
import type { ToolDefinition } from "./types.js";
import { allowedEnv, asObject, optionalNumber, optionalString, requiredString } from "./runtime.js";
interface ManagedProcess { id: string; command: string; cwd: string; child: ChildProcessWithoutNullStreams; startedAt: string; stdout: string; stderr: string; exitCode: number | null; signal: NodeJS.Signals | null; }
const processes = new Map<string, ManagedProcess>();
function append(current: string, chunk: Buffer | string, limit: number): string { const next = current + chunk.toString(); return Buffer.byteLength(next) <= limit ? next : Buffer.from(next).subarray(Buffer.byteLength(next) - limit).toString(); }
export const processTools: ToolDefinition[] = [
  { name: "process_start", description: "Inicia processo persistente e retorna um id para logs e encerramento.", risk: "execute", inputSchema: { type: "object", properties: { command: { type: "string" }, cwd: { type: "string" }, id: { type: "string" }, startupWaitMs: { type: "number" } }, required: ["command"], additionalProperties: false }, async execute(input, context) { const values = asObject(input); const command = requiredString(values, "command"); const cwd = context.resolvePath(optionalString(values, "cwd", ".")!); const id = optionalString(values, "id") || randomUUID(); if (processes.has(id)) throw new Error(`Processo ${id} já existe.`); const child = spawn(command, { cwd, env: allowedEnv(context.config), shell: true, windowsHide: true, stdio: ["pipe", "pipe", "pipe"] }); const managed: ManagedProcess = { id, command, cwd, child, startedAt: new Date().toISOString(), stdout: "", stderr: "", exitCode: null, signal: null }; child.stdout.on("data", (chunk) => managed.stdout = append(managed.stdout, chunk, context.config.maxOutputBytes)); child.stderr.on("data", (chunk) => managed.stderr = append(managed.stderr, chunk, context.config.maxOutputBytes)); child.on("close", (code, signal) => { managed.exitCode = code; managed.signal = signal; }); processes.set(id, managed); await new Promise((resolve) => setTimeout(resolve, Math.min(1000, optionalNumber(values, "startupWaitMs", 250)))); return { id, pid: child.pid, command, cwd, running: managed.exitCode === null }; } },
  { name: "process_list", description: "Lista processos persistentes iniciados pelo XCoder.", risk: "read", inputSchema: { type: "object", properties: {}, additionalProperties: false }, async execute() { return { processes: [...processes.values()].map((item) => ({ id: item.id, pid: item.child.pid, command: item.command, cwd: item.cwd, startedAt: item.startedAt, running: item.exitCode === null, exitCode: item.exitCode, signal: item.signal })) }; } },
  { name: "process_logs", description: "Lê stdout e stderr acumulados de um processo persistente.", risk: "read", inputSchema: { type: "object", properties: { id: { type: "string" }, tailBytes: { type: "number" } }, required: ["id"], additionalProperties: false }, async execute(input) { const values = asObject(input); const item = processes.get(requiredString(values, "id")); if (!item) throw new Error("Processo não encontrado."); const tail = Math.max(1, optionalNumber(values, "tailBytes", 32_000)); return { id: item.id, running: item.exitCode === null, exitCode: item.exitCode, stdout: Buffer.from(item.stdout).subarray(-tail).toString(), stderr: Buffer.from(item.stderr).subarray(-tail).toString() }; } },
  { name: "process_stop", description: "Encerra um processo persistente.", risk: "destructive", inputSchema: { type: "object", properties: { id: { type: "string" }, signal: { type: "string" } }, required: ["id"], additionalProperties: false }, async execute(input) { const values = asObject(input); const id = requiredString(values, "id"); const item = processes.get(id); if (!item) throw new Error("Processo não encontrado."); const signal = (optionalString(values, "signal", "SIGTERM") || "SIGTERM") as NodeJS.Signals; item.child.kill(signal); return { id, signal, stopped: true }; } }
];
